# Generated by Django 2.1.7 on 2019-04-04 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gestures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pacientID', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=1024)),
                ('repetitions', models.IntegerField()),
                ('default_difficulty', models.IntegerField()),
                ('decision_tree', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_b64', models.TextField()),
                ('contact', models.CharField(max_length=200)),
                ('nif', models.IntegerField()),
                ('birth_date', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
